In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Exercise 33:
x = np.array([1,2,3])
Y = np.array([12,15,16])

In [3]:
vander = np.vander(x)
print("Vander matrix: \n", vander)
print("Coefficients: \n", np.linalg.solve(vander, Y))

Vander matrix: 
 [[1 1 1]
 [4 2 1]
 [9 3 1]]
Coefficients: 
 [-1.  6.  7.]


In [5]:
polyfit = np.polyfit(x, Y, deg=2)
print("polyfit solution: \n", polyfit)

polyfit solution: 
 [-1.  6.  7.]


In [6]:
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
# finish this later

In [5]:
# Exercise 34:
x = np.arange(0,12,2) # Velocity (100 ft./sec)
Y = np.array([0, 2.9, 14.8, 39.6, 74.3, 119]) # Force (100 lb)

In [6]:
vander = np.vander(x)
coeffs_vander = np.linalg.solve(vander, Y)

print("Vander matrix: \n", vander)
print("Coefficients: \n", coeffs_vander)
print("poly1d with Vander: \n", np.poly1d(coeffs_vander)(7.5) * 100)

Vander matrix: 
 [[     0      0      0      0      0      1]
 [    32     16      8      4      2      1]
 [  1024    256     64     16      4      1]
 [  7776   1296    216     36      6      1]
 [ 32768   4096    512     64      8      1]
 [100000  10000   1000    100     10      1]]
Coefficients: 
 [ 0.00260417 -0.07005208  0.66145833 -1.19479167  1.7125      0.        ]
poly1d with Vander: 
 6483.83789062


In [7]:
coeffs_polyfit = np.polyfit(x, Y, deg=5)

print("Coefficients: \n", coeffs_polyfit)
print("poly1d with polyfit: \n",np.poly1d(coeffs_polyfit)(7.5) * 100)

Coefficients: 
 [  2.60416667e-03  -7.00520833e-02   6.61458333e-01  -1.19479167e+00
   1.71250000e+00  -5.13915779e-14]
poly1d with polyfit: 
 6483.83789062


In [8]:
# Exercise 34 (extra):
deg3_polyfit = np.polyfit(x, Y, deg=3)

print("polyfit (deg=3) solution: \n", deg3_polyfit)
print("poly1d with polyfit: \n",np.poly1d(deg3_polyfit)(7.5) * 100)

polyfit (deg=3) solution: 
 [-0.00462963  1.40962302 -1.7412037   0.17539683]
poly1d with polyfit: 
 6445.45386905
