In [21]:
import numpy as np

from numpy.linalg import solve, qr
from scipy.linalg import solve_triangular

In [8]:
# Exercise 27 (c):
W = np.matrix([[20, 30],
               [550, 500]])
b = np.matrix([[150],
               [2825]])

In [9]:
x = solve(W, b)

In [11]:
x

matrix([[1.5],
        [4. ]])

In [14]:
# Exercise 28 (c):
W = np.matrix([[27.6, 30.2],
               [3100, 6400],
               [250, 360]])
b = np.matrix([[162],
               [23610],
               [1623]])

In [22]:
Q, R = qr(W)

In [23]:
Q

matrix([[-0.00887407,  0.16889474],
        [-0.99672471, -0.0807233 ],
        [-0.08038102,  0.98232292]])

In [24]:
R

matrix([[-3110.18677253, -6408.24329139],
        [    0.        ,  -157.89223671]])

In [25]:
x = solve_triangular(R, Q.T @ b)

In [26]:
x

array([[3.9],
       [1.8]])